### PR TITLE
Removed get_secret(). #211

### PR DESCRIPTION
**Pull request by aacn500**
Replaced get_secret() with config.get(). I fixed the relevant test by using config.set(), and I can't see anywhere else that is affected by the change.
First time working with git and open source in general, apologies if I missed something obvious!

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the feedback! Can you also remove "Secret" class in https://github.com/google/personfinder/blob/master/app/model.py#L752 ?

**Comment by aacn500** [comment]
Should reset_database() in https://github.com/google/personfinder/blob/master/tools/setup_pf.py#L40 still keep what used to be Secrets (analytics_id and maps_api_key), or is that no longer required functionality?

**Comment by gimite** [comment]
It seems reset_database() is used in server test. Can you simply remove "Secret" from reset_database() and try running the server tests by this command?:

    tools/server_tests

Also, I found some other parts which still refer to secrets. Can you remove these too?:

- get_secret() in app/utils.py
- tests/server_test_cases/secret_tests.py (You can replace secrets by config here as well)
- import in app/reveal.py (I believe you can just delete it because it looks not used)

**Comment by aacn500** [comment]
These commits pass all server tests for me, and I can see no more references to the Secret class when running ```git grep -in secret```.

**Comment by gimite** [comment]
Thanks! Looks good to me.

Can you read through:
https://github.com/google/personfinder/blob/master/CONTRIBUTING.md
and sign this online form?:
https://cla.developers.google.com/about/google-individual

It is required by our company to accept patches from you.

**Comment by gimite** [comment]
As my personal note: I must migrate secrets into configs in our production before pushing this change to production.

**Comment by aacn500** [comment]
CLA has been submitted.

**Comment by gimite** [comment]
Merged. Thanks for  your contribution!

> As my personal note: I must migrate secrets into configs in our production before pushing this change to production.

Done.

**Pull request merged**
