### PR TITLE
Issue #354: Added specific version to pillow

### PR DESCRIPTION
**Pull request by RajibHossen**
Travis build was failing due to pillow version issue.
Changed pillow version to 4.1.0.

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the fix! Merged.

Looks like pillow 4.1.0 is a new version which has been just released. I found that CI has been fixed just by rerunning it (which picks up pillow 4.1.0) even without this PR. But I guess that fixing the library versions is better because it makes our CI more stable. There's pros&cons, though. We should fix the version of other libraries too if we go with this direction.

**Comment by RajibHossen** [comment]
Thanks @gimite 
yeah, I also think that. We can identify which specific version we need for each package rather depending on latest version. When there is need to update the whole project, then we can determine package inconsistencies and dependencies in a more controlled way. That's my thought too.

**Comment by AwesomeTurtle** [comment]
I also think that so we should freeze
 + lxml
 + cssselect
 + phusion/baseimage

And, @gimite I wondering if we need to freeze GAE too ?

**Comment by gimite** [comment]
Looks like AppEngine SDK is already frozen to 1.9.50?
https://github.com/google/personfinder/blob/master/Dockerfile#L29

**Pull request merged**
