### PR TITLE
Fix issue 128 - Mark duplicates table is too wide

### PR DESCRIPTION
**Pull request by iniju**

### CODE REVIEW

**Comment by iniju** [comment]
It affects the way the "Back to start" link appears. Hopefully you can see the attached images.

With end-multi-columns:
with end-multi-columns

Without end-multi-columns:
without end-multi-columns

**Comment by gimite** [comment]
How about omitting "end" class and just specify "column"? Then it won't introduce "float: left;", so I believe you don't need end-multi-columns.

**Comment by iniju** [comment]
Yeap, that works, I've updated the pull request.

**Comment by gimite** [comment]
LGTM. Thanks! Merged.

**Pull request merged**
