### PR TITLE
Adding a memcache feature for UX improvement.

### PR DESCRIPTION
**Pull request by githaruo**
#248 I've added a memcache feature for UX improvement. And I think someone working on DB to NDB also accelerate web page's speed.

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for making the change!

But I found that there's a race condition issue in this implementation.

Assume there's a config named "x" with initial value "a", and memcache is not populated. And there are two processes A and B which calls these methods at the same time:

Process A: config.get("x")
Process B: config.set(x="b")

Then it's possible that the two processes execute these operations in this order:

Process A: Read from memcache and get None
Process A: Read from datastore and get "a"
Process B: Write "b" to datastore
Process B: Write "b" to memcache
Process A: Write "a" to memcache

As a result, "b" is stored in datastore while "a" is stored in memcache, and this inconsistency is not resolved until 1 hour passes. This is something we want to avoid.

This article is discussing this issue:
https://cloud.google.com/appengine/articles/best-practices-for-app-engine-memcache#code_complexity_and_concurrency
And recommend to use NDB (which internally caches to memcache) rather than implementing memcache caching by ourselves:
> When using Memcache for data that is both read and modified, use the Python NDB Client Library. 

So it sounds like we should just wait for #346 and test again to see if we need any more memcache handling. What do you think? Sorry I should have found this earlier.

On the other hand, as we chatted before, there's another potential improvement for config; to put all configs for a repository to a single datastore entry, instead of storing them separately. I created #349 for it. If you are interested, it would be great if you work on it instead which is orthogonal to #346. (You might still want to wait until #346 is submitted before working on #349 to avoid code conflict, though.)

**Comment by githaruo** [comment]
I didn't notice that your suggestion is right it's hard to handle from multiple changes by this design.

Another thing I tested this version's render speed by using my browser. There is >200% faster than current version (1 sec is the average of current response time, memcache version shows 400msec-500msec). I hope that the integration to NDB will perform as much as this and also #349 makes more faster than ever seen.

Let's stop this pull request.

**Comment by gimite** [comment]
Thanks, that's a great news. Did you check by uploading it to AppEngine, or with the local dev appserver? Use AppEngine for this kind of measurement because the local dev appserver is implemented in a very different way and can show very different performance.

Let's measure it again after the NDB change is in. If it's not as fast as your memcache implementation, we may want to revisit using memcache directly.

**Comment by githaruo** [comment]
Of course, I uploaded it on my test app engine appspot.com and tested both **dedicated memcache** and **shared memcache** (free version). Both were similar score.

**Comment by gimite** [comment]
Great, thanks!

**Pull request closed without merging**
