### PR TITLE
First batch of yapf auto-formatting.

### PR DESCRIPTION
**Pull request by nworden**
This covers all our files under app/ which don't start with a, f, m, or v.

Starts addressing issue #619.

### CODE REVIEW

**Comment by nworden** [comment]
I'll do tests separately. I skipped some letters because I'm doing work on admin handlers, you have a pending change for frontend_api.py, I have a pending change for model.py, and vintol mentioned he's working on views.py.

**Comment by nworden** [comment]
Hm, I think I figured out why Jakub's PR had a lint failure: yapf had a release today, and I think it generated different output than before. I'm going to close this PR for now, and look into other auto-formatter options. yapf seemed like a good choice because it's from Google and would be sure to use the style guide we use, but maybe it'd be better to choose something more mature. Enforcing use of an auto-formatter with less-than-stable output seems like a real hassle.

**Comment by gimite** [comment]
If we cannot find a good alternative, does it make sense to stick to a specific version of yapf (and perform project-wide batch update when we feel the version is too old)?

**Comment by nworden** [comment]
Replied on issue #619

**Pull request closed without merging**
