### PR TITLE
Contains fix for bug #79

### PR DESCRIPTION
**Pull request by kspviswa**
It is quite a bug :) . The home country span element was missing the create.html.template file. I just added the same (copying from view.html.template). Also used the "trans" element to support language compatibility.

Unit tested & found OK. Attached screen shots.

Home country field now visible

image

image

Viewing the added record with the added Home  country

image

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the fix! I will take a look.

**Comment by gimite** [comment]
The change looks good to me. Before pulling your change, can you sign this agreement:
https://cla.developers.google.com/about/google-individual
This is required to accept patches from people outside our company, per our policy.

The CLA is necessary mainly because you own the
copyright to your changes, even after your contribution becomes part of our
codebase, so we need your permission to use and distribute your code.

**Comment by kspviswa** [comment]
@gimite 

Thanks for accepting my pull request. As directed, I had signed the CLA under individual category & tagged my github account (kspviswa) to it. Please let me know, if anything else is pending from my side.

BR,
Viswa

**Comment by gimite** [comment]
Cherry-picked c70b55e . Thanks!

**Pull request closed without merging**
