### PR TITLE
Third party requirement

### PR DESCRIPTION
**Pull request by AwesomeTurtle**
Create `app/lib`. Then `pip freeze` to get `requirements.txt`. 

Install dependencies into app/lib : `pip install -r requirements.txt -t app/lib`
Update dependencies into app/lib : `pip install -r requirements.txt -t app/lib --upgrade`

Some notes: 
 * Added `fix_path.py` into `app/` and imported it into `main.py` and `unit_tests.py` for include `lib`
 * Added `appengine_config.py` into `app/`
 * `Unidecode` is not in `requirements.txt` because last version of `Unidecode` produce fails

Sources:
[App Engine-Using lib python 27](https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27)

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the pull request!

Unfortunately the change is too big and it's almost impossible to do code review on Github. Can you create a new pull request (or maybe update this one) without deleting any libraries in app, and without adding app/lib? Then I can review changes in other files first. You can add changes to move the libraries after the review.

Among libraries in requirements.txt:

> Django==1.4

You don't need to include this. Django is added by app/app.yaml. It should also in AppEngine SDK for local environment.

> lxml==3.7.2

You shouldn't include this either. lxml is added by app/app.yaml. You still need to install it for local dev app server, but it contains platform-dependent native libraries (*.so), so you cannot put it in the repository. We should keep asking people to install manually with "pip install lxml", I believe.

> olefile==0.44
> Pillow==4.0.0
> py==1.4.32

It looks these are not in the current app/ directory. Why did you add these?

**Comment by AwesomeTurtle** [comment]
No worries, I am on it !

**Comment by gimite** [comment]
There are still 1541 changed files in this pull request:
https://github.com/google/personfinder/pull/322/files
Looks you haven't deleted app/lib yet? I still see app/lib/babel/AUTHORS etc. above.

**Comment by gimite** [comment]
Thanks for the clean up.

I tested it on my local dev app server, but it doesn't work for me. Is it working for you (after deleting libraries from app directory)?

I tried (without Docker):
```
$ git pull https://github.com/AwesomeTurtle/personfinder.git awesometurtle-third-party-requirement
$ pip install -r requirements.txt -t app/lib
$ rm -r app/babel app/pytz app/recaptcha app/simplejson app/xlrd
$ ./tools/gae run --port=19001 app
```
and accessed localhost:19001, and it failed with:
```
ImportError: No module named recaptcha.client
```
I use AppEngine SDK 1.9.49.

**Comment by AwesomeTurtle** [comment]
Yes, I had this problem. 
Indeed, when you are using 

    $ pip install -t app/lib -r requirements.txt

libs are installed in a folder. (e.g `Babel/babel/`) so you have to create an `__init__.py` file in each folder.

**Comment by gimite** [comment]
Hmm it's not the case for me. Libraries are added directly under app/lib (but still it doesn't load them). Did you confirm that they are wrapped with folders in your environment? Maybe the behavior differs by PIP versions...?

```
$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

$ pip install -r requirements.txt -t app/lib

$ ls app/lib
Babel-2.3.4.dist-info/                  recaptcha_client-1.0.6-py2.7.egg-info/
babel/                                  simplejson/
pytz/                                   simplejson-3.10.0-py2.7.egg-info/
pytz-2016.10.dist-info/                 xlrd/
recaptcha/                              xlrd-1.0.0-py2.7.egg-info/
recaptcha_client-1.0.6-py2.7-nspkg.pth

$ ls app/lib/babel 
__init__.py  dates.py      lists.py       localtime/  plural.py   util.py
_compat.py   global.dat    locale-data/   messages/   support.py
core.py      languages.py  localedata.py  numbers.py  units.py
```

**Comment by AwesomeTurtle** [comment]
hmmmm it's weird. 

```
    # pip --version
    pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

    # pip install -r requirements.txt -t app/lib

    # ls app/lib/
    Babel-2.3.4.dist-info                   recaptcha_client-1.0.6.dist-info
    babel                                   simplejson
    pytz                                    simplejson-3.10.0.dist-info
    pytz-2016.10.dist-info                  xlrd
    recaptcha                               xlrd-1.0.0.dist-info
    recaptcha_client-1.0.6-py2.7-nspkg.pth

    # ls app/lib/babel/
    __init__.py   dates.py       lists.pyc       numbers.py   units.py
    __init__.pyc  dates.pyc      locale-data     numbers.pyc  units.pyc
    _compat.py    global.dat     localedata.py   plural.py    util.py
    _compat.pyc   languages.py   localedata.pyc  plural.pyc   util.pyc
    core.py       languages.pyc  localtime       support.py
    core.pyc      lists.py       messages        support.pyc

```

And so you can see an `__init__.pyc` into `app/lib/babel`  showing this lib is  called... 

As you said, maybe there is a problem with pip version. I am going to check with your pip version.

**Comment by AwesomeTurtle** [comment]
So I checked again. In fact `recaptcha.client` is wrapped as `recaptcha/client/...` so you can't call `recaptcha.client` if `__init__.py` is not in `recaptcha`

```
$ ls app/lib/recaptcha
client

$ touch app/lib/recaptcha/__init__.py

$ ls app/lib/recaptcha               
client  __init__.py


```

Also, `unidecode` is missing in `requirements.txt` but after those modifications, everything works ! So if it works for you, I will close this pull requests and open another one to keep things "clean".

**Comment by gimite** [comment]
Oh I see.

But I have just found that our app/recaptcha is not a bare version of recaptcha-client 1.0.5. It has been modified to use Recaptcha API v2. So it will be broken if we replace it with the bare recaptcha-client. Can you keep app/recaptcha as is instead of installing it via pip? Sorry I have completely forgotten that.

FYI You can verify that reCaptcha is working by running a dev app server, creating a new person record with "Subscribe for updates about your record" option checked (which is default).

**Comment by gimite** [comment]
Thanks for the change! But it looks the change became larger again (with 1500 files), so I cannot review other files. Can you revert deleting libraries in app directory so that I can review other files?

Also, please keep recaptcha library at app/recaptcha, not app/lib/recaptcha. I want to make app/lib a directory to put only unmodified libraries installed via pip. It may be better to rename app/lib to app/vendors to make it clear.

**Comment by gimite** [comment]
@AwesomeTurtle Just wondering, why did you close this pull request?

**Comment by AwesomeTurtle** [comment]
@gimite Good advance, but not I have not good habilities with git workflow .. So I will be back in a few time. In waiting, issue is still open so people who want to contribute can do it !

**Comment by gimite** [comment]
So are you still actively working on it? That would be great, thanks! It's unfortunate that it's tricky to handle a change with large number of files on Github...

**Pull request closed without merging**
