### PR TITLE
Fixes #525: Corrected Repo Header Link to go to Homepage

### LINKED ISSUE #525: Back button in RepoHeader doesn't takes back
When on clicking the back button on repo header, it doesn't go to the previous page and remains on the same page itself.

I am sending the patch for this.

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #525: Fixed the Repo Header link to go to home page.

### CODE REVIEW

**Comment by yashLadha** [comment]
I signed it!

**Comment by yashLadha** [comment]
@nworden Please review this

**Comment by nworden** [comment]
Hey Yash! Thanks for this fix!
I'll talk with our UXer about whether we ought to have a back button on the homepage at all: during crises, people often follow links from social media, etc. that go directly to the repo homepage rather than the global homepage, so maybe we ought to leave the back button off the homepage altogether, but that's a UX decision. If we keep the back button, having it go to the global homepage makes more sense to me than having it go nowhere, so I'll merge in this PR.

**Comment by yashLadha** [comment]
Sound's good @nworden . Also, I would like to know the perspective on static pages as well. Like should I create a HOC for all these components or create an interface from which they all get extended.

**Comment by nworden** [comment]
Just FTR, I continued the discussion on issue #478.

**Pull request merged**
